### PR TITLE
Fix first last index

### PR DESCRIPTION
**Pull request by oscarwyatt**
Fix a problem displaying the first chronologically first and last visits (go to /visits and click on the first or last, this should fix that)

Fix link issue on /visits with links in content list (ultimately, we'll probably get rid of this)

### CODE REVIEW

**Comment by sophiebrown01** [comment]
Is it worth combining these commits? If you could also detail what the bug was that'd be great, for our future selves

**Comment by oscarwyatt** [comment]
They're separate issues so I don't really feel it makes sense to squash the commits (unless you really want to, if so happy to). I've made the commit messages more descriptive though, good shout 💯

**Comment by sophiebrown01** [comment]
Great, thanks for adding that detail into the commit messages. Happy to keep them as separate given they're separate issues.

**Review by sophiebrown01 — APPROVED** [review]
🚀

**Pull request merged**
